// Fill out your copyright notice in the Description page of Project Settings.


#include "TpsPlayer.h"
#include <GameFramework/SpringArmComponent.h>
#include <Camera/CameraComponent.h>
#include <GameFramework/CharacterMovementComponent.h>
#include "Bullet.h"
#include <Blueprint/UserWidget.h>
#include <Kismet/GameplayStatics.h>
#include <Particles/ParticleSystem.h>
#include "Enemy.h"
#include "EnemyFSM.h"
#include <Components/CapsuleComponent.h>
#include "ABP_Player.h"
#include "PlayerMove.h"
#include "PlayerFire.h"
#include "MainUI.h"
#include "Minimap.h"
#include "GameOverUI.h"


// Sets default values
ATpsPlayer::ATpsPlayer()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	//Mesh 위치와 회전을 셋팅
	GetMesh()->SetRelativeLocation(FVector(0, 0, -90));
	//pitch - yaw - roll
	GetMesh()->SetRelativeRotation(FRotator(0, -90, 0));
	//외형(Skeletal Mesh) 를 로드해서 셋팅하자
	ConstructorHelpers::FObjectFinder<USkeletalMesh> tempMesh(TEXT("SkeletalMesh'/Game/AnimStarterPack/UE4_Mannequin/Mesh/SK_Mannequin.SK_Mannequin'"));
	if (tempMesh.Succeeded())
	{
		GetMesh()->SetSkeletalMesh(tempMesh.Object);
	}

	//SpringArmComponent
	compArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("ARM"));
	compArm->SetupAttachment(RootComponent);
	compArm->SetRelativeLocation(FVector(0, 70, 90));
	compArm->TargetArmLength = 300;

	//CameraComponent
	compCam = CreateDefaultSubobject<UCameraComponent>(TEXT("CAM"));
	compCam->SetupAttachment(compArm);

	//SkeltalMeshComponent 셋팅 (Rifle)
	compRifle = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("RIFLE"));
	compRifle->SetupAttachment(GetMesh(), TEXT("WeaponPos"));
	compRifle->SetRelativeLocation(FVector(-17, 10, -3));
	compRifle->SetRelativeRotation(FRotator(0, 90, 0));

	//SkeltalMesh 불러와서 셋팅
	ConstructorHelpers::FObjectFinder<USkeletalMesh> tempRifle(TEXT("SkeletalMesh'/Game/FPWeapon/Mesh/SK_FPGun.SK_FPGun'"));
	if (tempRifle.Succeeded())
	{
		compRifle->SetSkeletalMesh(tempRifle.Object);
	}

	//StaticMeshComponent 셋팅(Sniper)
	compSniper = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("SNIPER"));
	compSniper->SetupAttachment(GetMesh(), TEXT("WeaponPos"));

	compSniper->SetRelativeLocation(FVector(-42, 7, 1));
	compSniper->SetRelativeRotation(FRotator(0, 90, 0));
	compSniper->SetRelativeScale3D(FVector(0.15f));

	//StaticMesh 블러와서 셋팅
	ConstructorHelpers::FObjectFinder<UStaticMesh> tempSniper(TEXT("StaticMesh'/Game/SniperGun/sniper1.sniper1'"));
	if (tempSniper.Succeeded())
	{
		compSniper->SetStaticMesh(tempSniper.Object);
	}
	

	//애니메이션 블루프린트 가져오자
	ConstructorHelpers::FClassFinder<UABP_Player> tempAnim(TEXT("AnimBlueprint'/Game/Blueprints/ABP_Player.ABP_Player_C'"));
	if (tempAnim.Succeeded())
	{
		GetMesh()->SetAnimInstanceClass(tempAnim.Class);
	}

	//PlayerMove 컴포넌트 붙이자
	compPlayerMove = CreateDefaultSubobject<UPlayerMove>(TEXT("MOVE"));
	//PlayerFire 컴포넌트 붙이자
	compPlayerFire = CreateDefaultSubobject<UPlayerFire>(TEXT("ATTACK"));

	//MainUI 클래스 찾아오자
	ConstructorHelpers::FClassFinder<UMainUI> tempMainUI(TEXT("WidgetBlueprint'/Game/Blueprints/BP_MainUI.BP_MainUI_C'"));
	if (tempMainUI.Succeeded())
	{
		mainUIFactory = tempMainUI.Class;
	}

	//MiniMap 클래스 찾아오자
	ConstructorHelpers::FClassFinder<AMinimap> tempMini(TEXT("Blueprint'/Game/Blueprints/BP_Minimap.BP_Minimap_C'"));
	if (tempMini.Succeeded())
	{
		miniFactory = tempMini.Class;
	}

	ConstructorHelpers::FClassFinder<UGameOverUI> tempGameOverUI(TEXT("WidgetBlueprint'/Game/Blueprints/BP_GameOverUI.BP_GameOverUI_C'"));
	if (tempGameOverUI.Succeeded())
	{
		gameOverUIFactory = tempGameOverUI.Class;
	}

	//Camera Shake 블루프린트 가져오자
	/*ConstructorHelpers::FClassFinder<UCameraShakeBase> tempCam(TEXT("Blueprint'/Game/Blueprints/BP_CameraShake.BP_CameraShake_C'"));
	if (tempCam.Succeeded())
	{
		cameraShake = tempCam.Class;
	}*/	
}

// Called when the game starts or when spawned
void ATpsPlayer::BeginPlay()
{
	//MainUI 생성 후 Viewport 에 붙이자
	mainUI = CreateWidget<UMainUI>(GetWorld(), mainUIFactory);
	mainUI->AddToViewport();

	Super::BeginPlay();

	//CapsuleCompoenent 의 ECC_Visibility -> ECR_Block 로 셋팅
	GetCapsuleComponent()->SetCollisionResponseToChannel(ECC_Visibility, ECR_Block);

	//현재 HP 를 최기화
	currHP = maxHP;
	prevHP = maxHP;

	//Minimap 생성하자
	GetWorld()->SpawnActor<AMinimap>(
		miniFactory, 
		FVector(GetActorLocation().X, GetActorLocation().Y, 540),
		FRotator(-90, 0, 0));

	//bUseControllerRotationYaw = false;
	//compArm->bUsePawnControlRotation = false;

	
}

// Called every frame
void ATpsPlayer::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
		

	prevHP = FMath::Lerp(prevHP, currHP, DeltaTime * 20);
	mainUI->UpdateCurrHP(prevHP, maxHP);

	//만약에 HP UI 갱신해야 한다면
	//if (bUpdateHP == true)
	//{
	//	ratioHP += DeltaTime * 2;
	//	//목적지에 도달했으면 초기화
	//	if (ratioHP >= 1)
	//	{
	//		ratioHP = 1;
	//		bUpdateHP = false;
	//	}

	//	//HP UI 를 생신하자
	//	float hp = FMath::Lerp(prevHP, currHP, ratioHP);
	//	mainUI->UpdateCurrHP(hp, maxHP);		
	//}
	
}

// Called to bind functionality to input
void ATpsPlayer::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	//PlayerMove 키 등록
	compPlayerMove->SetupInputBinding(PlayerInputComponent);
	//PlayerFire 키 등록
	compPlayerFire->SetupInputBinding(PlayerInputComponent);
}

void ATpsPlayer::ReceiveDamage(float damage)
{
	//이전 HP 를 저장한다.
	//prevHP = currHP;
	bUpdateHP = true;
	ratioHP = 0;

	//현재 HP 를 damage 만큼 줄여준다.
	currHP -= damage;

	//HP UI 갱신
	//mainUI->UpdateCurrHP(currHP, maxHP);

	//만약에 HP 가 0보다 같거나 작다면
	if (currHP <= 0)
	{
		//gameOverUI 생성 후 Viewport 에 붙이자
		UGameOverUI* ui = CreateWidget<UGameOverUI>(GetWorld(), gameOverUIFactory);
		ui->AddToViewport();
	}
	//그렇지 않다면
	else
	{
		//현재HP 를 출력
		UE_LOG(LogTemp, Warning, TEXT("Curr HP : %f"), currHP);
	}
}


